#!/usr/bin/perl

use strict;
use warnings;

my $offset_file         = 'offset_database.txt';
my $sorted_file         = 'sorted_database.txt';
my $original_pseudocode = 'cod2_lnxded_1_0.c.original';
my $created_pseudocode  = 'cod2_lnxded_1_0.c';

print "Opening files...\n";
open(OFFSET_FILE,         '<' . $offset_file)         or die("Error: Cannot open offset file.\n");
open(SORTED_FILE,         '>' . $sorted_file)         or die("Error: Cannot create sorted file.\n");
open(ORIGINAL_PSEUDOCODE, '<' . $original_pseudocode) or die("Error: Cannot open original pseudocode file.\n");
open(CREATED_PSEUDOCODE,  '>' . $created_pseudocode)  or die("Error: Cannot create new pseudocode file.\n");

my %offsets;
my %sorted_functions;
my %sorted_variables;
my @keys;
my $line;
my $key;
my $file;

print "Parsing offset file...\n";
while (defined($line = <OFFSET_FILE>)) {
	if ($line =~ /0[xX]0([0-9a-fA-F]+)/) {
		next if ($line =~ /^s?+\/\//);
		my $offset = $1;

		if ($line =~ /\(DWORD\)(\w+\.?\w+)/) {
			my $variable = $1;

			if (defined($offsets{$offset})) { die("Error: Duplicate offset found: $offset Aborting.\n"); }

			foreach $key (keys %offsets) {
				if ($variable eq $offsets{$key}) { die("Error: Duplicate variable found: $variable\n"); }
			}

			$offsets{$offset} = $variable;
			
						if ($line =~ /^SetJump/) {
				$sorted_functions{$offset} = $variable;
			}
			elsif ($line =~ /^SetDword/) {
				$sorted_variables{$offset} = $variable;
			}
		}
	}
}

print "Parsing original pseudocode file...\n";
$file = '';
while (defined($line = <ORIGINAL_PSEUDOCODE>)) {
	$file = $file . $line;
}

print "Replacing offsets in pseudocode file...\n";
foreach $key (keys %offsets) {
	$file =~ s/(byte_|dword_|sub_|unk_)$key/$offsets{$key}/g;
}

print "Writing new pseudocode file...\n";
print CREATED_PSEUDOCODE $file;

print "Writing sorted offset file...\n";
printf SORTED_FILE "// This file was autogenerated by replace_offsets.pl";
@keys = sort { $a cmp $b } keys %sorted_functions;
printf SORTED_FILE "\n\n// =================================== Functions ===================================\n\n";
foreach $key ( @keys ) {
    printf SORTED_FILE "SetJump(0x0$key, (DWORD)$sorted_functions{$key});\n";
}
@keys = sort { $a cmp $b } keys %sorted_variables;
printf SORTED_FILE "\n\n// =================================== Variables ===================================\n\n";
foreach $key ( @keys ) {
    printf SORTED_FILE "SetJump(0x0$key, (DWORD)$sorted_variables{$key});\n";
}

print "Closing files...\n";
close OFFSET_FILE;
close ORIGINAL_PSEUDOCODE;
close CREATED_PSEUDOCODE;

die "Done!\n";
